### PR TITLE
add task deployment test cases

### PR DESCRIPTION
**Pull request by swan-alexchen**

### CODE REVIEW

**Comment by alphaflows** [comment]
when I test this with sdk 0.0.7 (web3==6.15.1), I got error `cannot import name 'ContractName' from 'eth_typing'`

after I upgraded web3 to 6.20.3, it's good now
